/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import entidades.*;
import Utilidades.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Rene2
 */
public class Dialogo_Agregar_Examen extends javax.swing.JDialog {

    public Estudiante entidadActual;
    public Asignatura entidadSecundaria;

    /**
     * Creates new form Dialogo_Agregar_Asignatura
     */
    public Dialogo_Agregar_Examen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        UtilidadesParaVentana.ponerIconoDeVentana_Principal(this);

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.install(FF_Fecha);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

    }

    public void resetear(Estudiante e,Asignatura a) {
        this.entidadActual = e;
        this.entidadSecundaria=a;

        CB_Nota.setSelectedIndex(3);

        UtilidadesParaVentana.ponerFechaActual(FF_Fecha);
        CB_Numero.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        B_Cancelar = new javax.swing.JButton();
        B_Aceptar = new javax.swing.JButton();
        CB_Numero = new javax.swing.JComboBox<>();
        CB_Nota = new javax.swing.JComboBox<>();
        FF_Fecha = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Asignatura");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("Fecha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel2.setText("Nota:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel6.setText("Número:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        B_Cancelar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        B_Cancelar.setText("Cancelar");
        B_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(B_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));

        B_Aceptar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        B_Aceptar.setText("Aceptar");
        B_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(B_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 180, -1));

        CB_Numero.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        CB_Numero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(CB_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, 35));

        CB_Nota.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        CB_Nota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel1.add(CB_Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 250, 35));

        FF_Fecha.setText("jFormattedTextField1");
        jPanel1.add(FF_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_B_CancelarActionPerformed

    private void B_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AceptarActionPerformed
        try {
            String fechaStr = FF_Fecha.getText();

            String nota = CB_Nota.getSelectedItem().toString();

            String numero = CB_Numero.getSelectedItem().toString();

            if (MetodosValidacion.validar_es_nueva_Convocatoria_correcta(this,entidadSecundaria,entidadActual,numero, fechaStr)) {
                Date fecha=UtilidadesParaVentana.obtenerFecha(fechaStr); 
                Convocatoria nuevo = EnMemoria.BD.agregarConvocatoria(entidadSecundaria,entidadActual, nota, numero, fecha);
                EnMemoria.ventana_Principal.actualizar_Convocatoria(nuevo);
                setVisible(false);
                DLG_Respuesta.mostrarDlgExito(this, "Examen agregado con éxito  ");
            }
        } catch (Exception ex) {
            DLG_Respuesta.mostrarDlg_ErrorEnLaBD(this, ex);
        }

    }//GEN-LAST:event_B_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Agregar_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Agregar_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Agregar_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Agregar_Examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo_Agregar_Examen dialog = new Dialogo_Agregar_Examen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Aceptar;
    private javax.swing.JButton B_Cancelar;
    private javax.swing.JComboBox<String> CB_Nota;
    private javax.swing.JComboBox<String> CB_Numero;
    private javax.swing.JFormattedTextField FF_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
