/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author Rene2
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L_Facultades = new javax.swing.JLabel();
        B_Agregar_Facultades = new javax.swing.JButton();
        B_Editar_Facultades = new javax.swing.JButton();
        B_Eliminar_Facultades = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Facultades = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        T_Carrera = new javax.swing.JTable();
        B_Agregar_Carrera = new javax.swing.JButton();
        B_Editar_Carrera = new javax.swing.JButton();
        B_Eliminar_Carrera = new javax.swing.JButton();
        L_Carrera = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        T_Estudiantes = new javax.swing.JTable();
        B_Eliminar_Asignaturas = new javax.swing.JButton();
        B_Editar_Asignaturas = new javax.swing.JButton();
        B_Agregar_Asignaturas = new javax.swing.JButton();
        L_Asignaturas = new javax.swing.JLabel();
        L_Profesor = new javax.swing.JLabel();
        B_Agregar_Profesor = new javax.swing.JButton();
        B_Editar_Profesor = new javax.swing.JButton();
        B_Eliminar_Profesor = new javax.swing.JButton();
        B_Agregar_Estudiantes = new javax.swing.JButton();
        B_Editar_Estudiantes = new javax.swing.JButton();
        B_Eliminar_Estudiantes = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        T_Asignaturas = new javax.swing.JTable();
        L_Estudiantes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        L_Profesor_Nombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        T_Examenes = new javax.swing.JTable();
        B_Eliminar_Examenes = new javax.swing.JButton();
        B_Editar_Examenes = new javax.swing.JButton();
        B_Agregar_Examenes = new javax.swing.JButton();
        L_Examenes = new javax.swing.JLabel();
        L_Profesor_Apellidos = new javax.swing.JLabel();
        TI_Filtro_Locales = new javax.swing.JTextField();
        B_Filtrar_Locales = new javax.swing.JButton();
        B_Invertir_Orden_Locales = new javax.swing.JButton();
        B_Invertir_Orden_Locales1 = new javax.swing.JButton();
        B_Filtrar_Locales1 = new javax.swing.JButton();
        TI_Filtro_Locales1 = new javax.swing.JTextField();
        TI_Filtro_Locales2 = new javax.swing.JTextField();
        B_Filtrar_Locales2 = new javax.swing.JButton();
        B_Invertir_Orden_Locales2 = new javax.swing.JButton();
        TI_Filtro_Locales3 = new javax.swing.JTextField();
        B_Filtrar_Locales3 = new javax.swing.JButton();
        B_Invertir_Orden_Locales3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_Facultades.setText("Facultades");
        jPanel1.add(L_Facultades, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 220, -1));

        B_Agregar_Facultades.setText("+");
        B_Agregar_Facultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Agregar_FacultadesActionPerformed(evt);
            }
        });
        jPanel1.add(B_Agregar_Facultades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 45, 40));

        B_Editar_Facultades.setText("d");
        jPanel1.add(B_Editar_Facultades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 45, 40));

        B_Eliminar_Facultades.setText("-");
        jPanel1.add(B_Eliminar_Facultades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 45, 40));

        T_Facultades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Informatica"},
                {"Matematica"},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(T_Facultades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 270, 150));

        T_Carrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ingenieria Informatica"},
                {"Licenciatura Informatica"},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane2.setViewportView(T_Carrera);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 220, 150));

        B_Agregar_Carrera.setText("+");
        jPanel1.add(B_Agregar_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 45, 40));

        B_Editar_Carrera.setText("d");
        jPanel1.add(B_Editar_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 45, 40));

        B_Eliminar_Carrera.setText("-");
        jPanel1.add(B_Eliminar_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 45, 40));

        L_Carrera.setText("Carreras");
        jPanel1.add(L_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 220, -1));

        T_Estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Juan Jasinto", "Guanlberto Gomes", "1"},
                {"Miguel Lucas", "Santos Casa", null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Grupo"
            }
        ));
        jScrollPane3.setViewportView(T_Estudiantes);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 380, 150));

        B_Eliminar_Asignaturas.setText("-");
        jPanel1.add(B_Eliminar_Asignaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 45, 40));

        B_Editar_Asignaturas.setText("d");
        jPanel1.add(B_Editar_Asignaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 45, 40));

        B_Agregar_Asignaturas.setText("+");
        jPanel1.add(B_Agregar_Asignaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 45, 40));

        L_Asignaturas.setText("Asignaturas");
        jPanel1.add(L_Asignaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 220, -1));

        L_Profesor.setText("Profesor");
        jPanel1.add(L_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 220, -1));

        B_Agregar_Profesor.setText("+");
        jPanel1.add(B_Agregar_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 45, 40));

        B_Editar_Profesor.setText("d");
        jPanel1.add(B_Editar_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 45, 40));

        B_Eliminar_Profesor.setText("-");
        jPanel1.add(B_Eliminar_Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 45, 40));

        B_Agregar_Estudiantes.setText("+");
        jPanel1.add(B_Agregar_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 45, 40));

        B_Editar_Estudiantes.setText("d");
        jPanel1.add(B_Editar_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 45, 40));

        B_Eliminar_Estudiantes.setText("-");
        jPanel1.add(B_Eliminar_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 45, 40));

        T_Asignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Matamica", "Presencial", "Primer"},
                {"Español", "Turno", "Segundo"},
                {"Programacion", "Presencial", "Primer"},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Modalidad", "Semestre"
            }
        ));
        jScrollPane5.setViewportView(T_Asignaturas);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 290, 150));

        L_Estudiantes.setText("Estudiantes");
        jPanel1.add(L_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 220, -1));

        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        L_Profesor_Nombre.setText("nombre...");
        jPanel1.add(L_Profesor_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        jLabel8.setText("Apellidos: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        T_Examenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5", "1", "01-02-23"},
                {"4", "2", "05-04-23"},
                {"3", "3", null},
                {null, null, null}
            },
            new String [] {
                "Nota", "Numero", "Fecha"
            }
        ));
        jScrollPane6.setViewportView(T_Examenes);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 390, 150));

        B_Eliminar_Examenes.setText("-");
        jPanel1.add(B_Eliminar_Examenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 45, 40));

        B_Editar_Examenes.setText("d");
        jPanel1.add(B_Editar_Examenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 45, 40));

        B_Agregar_Examenes.setText("+");
        jPanel1.add(B_Agregar_Examenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 45, 40));

        L_Examenes.setText("Exámenes");
        jPanel1.add(L_Examenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 220, -1));

        L_Profesor_Apellidos.setText("apellidos...");
        jPanel1.add(L_Profesor_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        TI_Filtro_Locales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TI_Filtro_LocalesActionPerformed(evt);
            }
        });
        jPanel1.add(TI_Filtro_Locales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, 35));

        B_Filtrar_Locales.setToolTipText("Buscar según la entrada ");
        B_Filtrar_Locales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Filtrar_LocalesActionPerformed(evt);
            }
        });
        jPanel1.add(B_Filtrar_Locales, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 45, 40));

        B_Invertir_Orden_Locales.setToolTipText("Cambiar dirección del orden de los datos mostrados en la tabla ");
        B_Invertir_Orden_Locales.setMargin(new java.awt.Insets(2, 2, 2, 2));
        B_Invertir_Orden_Locales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Invertir_Orden_LocalesActionPerformed(evt);
            }
        });
        jPanel1.add(B_Invertir_Orden_Locales, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 45, 40));

        B_Invertir_Orden_Locales1.setToolTipText("Cambiar dirección del orden de los datos mostrados en la tabla ");
        B_Invertir_Orden_Locales1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        B_Invertir_Orden_Locales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Invertir_Orden_Locales1ActionPerformed(evt);
            }
        });
        jPanel1.add(B_Invertir_Orden_Locales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 45, 40));

        B_Filtrar_Locales1.setToolTipText("Buscar según la entrada ");
        B_Filtrar_Locales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Filtrar_Locales1ActionPerformed(evt);
            }
        });
        jPanel1.add(B_Filtrar_Locales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 45, 40));

        TI_Filtro_Locales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TI_Filtro_Locales1ActionPerformed(evt);
            }
        });
        jPanel1.add(TI_Filtro_Locales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 240, 35));

        TI_Filtro_Locales2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TI_Filtro_Locales2ActionPerformed(evt);
            }
        });
        jPanel1.add(TI_Filtro_Locales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 330, 35));

        B_Filtrar_Locales2.setToolTipText("Buscar según la entrada ");
        B_Filtrar_Locales2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Filtrar_Locales2ActionPerformed(evt);
            }
        });
        jPanel1.add(B_Filtrar_Locales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 60, 45, 40));

        B_Invertir_Orden_Locales2.setToolTipText("Cambiar dirección del orden de los datos mostrados en la tabla ");
        B_Invertir_Orden_Locales2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        B_Invertir_Orden_Locales2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Invertir_Orden_Locales2ActionPerformed(evt);
            }
        });
        jPanel1.add(B_Invertir_Orden_Locales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 60, 45, 40));

        TI_Filtro_Locales3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TI_Filtro_Locales3ActionPerformed(evt);
            }
        });
        jPanel1.add(TI_Filtro_Locales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 240, 35));

        B_Filtrar_Locales3.setToolTipText("Buscar según la entrada ");
        B_Filtrar_Locales3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Filtrar_Locales3ActionPerformed(evt);
            }
        });
        jPanel1.add(B_Filtrar_Locales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 45, 40));

        B_Invertir_Orden_Locales3.setToolTipText("Cambiar dirección del orden de los datos mostrados en la tabla ");
        B_Invertir_Orden_Locales3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        B_Invertir_Orden_Locales3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Invertir_Orden_Locales3ActionPerformed(evt);
            }
        });
        jPanel1.add(B_Invertir_Orden_Locales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 45, 40));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_Agregar_FacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Agregar_FacultadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Agregar_FacultadesActionPerformed

    private void TI_Filtro_LocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TI_Filtro_LocalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TI_Filtro_LocalesActionPerformed

    private void B_Filtrar_LocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Filtrar_LocalesActionPerformed
       
    }//GEN-LAST:event_B_Filtrar_LocalesActionPerformed

    private void B_Invertir_Orden_LocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Invertir_Orden_LocalesActionPerformed
       
    }//GEN-LAST:event_B_Invertir_Orden_LocalesActionPerformed

    private void B_Invertir_Orden_Locales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Invertir_Orden_Locales1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Invertir_Orden_Locales1ActionPerformed

    private void B_Filtrar_Locales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Filtrar_Locales1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Filtrar_Locales1ActionPerformed

    private void TI_Filtro_Locales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TI_Filtro_Locales1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TI_Filtro_Locales1ActionPerformed

    private void TI_Filtro_Locales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TI_Filtro_Locales2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TI_Filtro_Locales2ActionPerformed

    private void B_Filtrar_Locales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Filtrar_Locales2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Filtrar_Locales2ActionPerformed

    private void B_Invertir_Orden_Locales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Invertir_Orden_Locales2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Invertir_Orden_Locales2ActionPerformed

    private void TI_Filtro_Locales3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TI_Filtro_Locales3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TI_Filtro_Locales3ActionPerformed

    private void B_Filtrar_Locales3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Filtrar_Locales3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Filtrar_Locales3ActionPerformed

    private void B_Invertir_Orden_Locales3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Invertir_Orden_Locales3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Invertir_Orden_Locales3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Agregar_Asignaturas;
    private javax.swing.JButton B_Agregar_Carrera;
    private javax.swing.JButton B_Agregar_Estudiantes;
    private javax.swing.JButton B_Agregar_Examenes;
    private javax.swing.JButton B_Agregar_Facultades;
    private javax.swing.JButton B_Agregar_Profesor;
    private javax.swing.JButton B_Editar_Asignaturas;
    private javax.swing.JButton B_Editar_Carrera;
    private javax.swing.JButton B_Editar_Estudiantes;
    private javax.swing.JButton B_Editar_Examenes;
    private javax.swing.JButton B_Editar_Facultades;
    private javax.swing.JButton B_Editar_Profesor;
    private javax.swing.JButton B_Eliminar_Asignaturas;
    private javax.swing.JButton B_Eliminar_Carrera;
    private javax.swing.JButton B_Eliminar_Estudiantes;
    private javax.swing.JButton B_Eliminar_Examenes;
    private javax.swing.JButton B_Eliminar_Facultades;
    private javax.swing.JButton B_Eliminar_Profesor;
    private javax.swing.JButton B_Filtrar_Locales;
    private javax.swing.JButton B_Filtrar_Locales1;
    private javax.swing.JButton B_Filtrar_Locales2;
    private javax.swing.JButton B_Filtrar_Locales3;
    private javax.swing.JButton B_Invertir_Orden_Locales;
    private javax.swing.JButton B_Invertir_Orden_Locales1;
    private javax.swing.JButton B_Invertir_Orden_Locales2;
    private javax.swing.JButton B_Invertir_Orden_Locales3;
    private javax.swing.JLabel L_Asignaturas;
    private javax.swing.JLabel L_Carrera;
    private javax.swing.JLabel L_Estudiantes;
    private javax.swing.JLabel L_Examenes;
    private javax.swing.JLabel L_Facultades;
    private javax.swing.JLabel L_Profesor;
    private javax.swing.JLabel L_Profesor_Apellidos;
    private javax.swing.JLabel L_Profesor_Nombre;
    private javax.swing.JTextField TI_Filtro_Locales;
    private javax.swing.JTextField TI_Filtro_Locales1;
    private javax.swing.JTextField TI_Filtro_Locales2;
    private javax.swing.JTextField TI_Filtro_Locales3;
    private javax.swing.JTable T_Asignaturas;
    private javax.swing.JTable T_Carrera;
    private javax.swing.JTable T_Estudiantes;
    private javax.swing.JTable T_Examenes;
    private javax.swing.JTable T_Facultades;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
